[package]
name = "hello-sqlx-sqlite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.1.0"
sqlx = { version = "0.6.0", features = ["runtime-actix-native-tls", "offline", "sqlite"] }
